-- 코드를 입력하세요
SELECT uu.USER_ID, uu.NICKNAME, 
    CONCAT(uu.CITY, ' ', uu.STREET_ADDRESS1, ' ', uu.STREET_ADDRESS2) '전체주소',
    CONCAT(SUBSTRING(uu.TLNO, 1, 3), '-', SUBSTRING(uu.TLNO, 4, 4), '-', SUBSTRING(uu.TLNO, 8, 4)) '전화번호'
FROM USED_GOODS_USER uu
JOIN USED_GOODS_BOARD ub
ON uu.USER_ID = ub.WRITER_ID
GROUP BY uu.USER_ID
HAVING count(*) >= 3
ORDER BY uu.USER_ID DESC;

# SELECT *
# FROM USED_GOODS_USER uu
# JOIN USED_GOODS_BOARD ub
# ON uu.USER_ID = ub.WRITER_ID