SELECT uu.USER_ID, uu.NICKNAME, sum(ub.PRICE) 'TOTAL_SALES'
FROM USED_GOODS_USER uu
JOIN USED_GOODS_BOARD ub
ON uu.USER_ID = ub.WRITER_ID
WHERE ub.STATUS = 'DONE'
GROUP BY uu.USER_ID
HAVING sum(ub.PRICE) >= 700000
ORDER BY sum(ub.PRICE);