-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', uf.BOARD_ID,'/', uf.FILE_ID, uf.FILE_NAME, uf.FILE_EXT) as FILE_PATH
FROM USED_GOODS_BOARD ub
LEFT JOIN USED_GOODS_FILE uf
ON ub.BOARD_ID = uf.BOARD_ID
WHERE ub.VIEWS = (SELECT max(u.VIEWS) FROM USED_GOODS_BOARD u)
ORDER BY ub.VIEWS desc